spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pymysql_study
    username: root
    password: "!Dydekd7511"

mybatis:
  mapper-locations:
    - /mappers/*.xml

root:
  path:  C:/python/upload/